services:
  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter:latest
    environment:
      - PIHOLE_HOSTNAME=${PIHOLE_HOSTNAME}
      - PIHOLE_PASSWORD=${PIHOLE_PASSWORD}
      - INTERVAL=90s
      - PORT=9617
    ports:
      - "9617:9617"
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower:arm64v8-latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_DISCORD_NOTIFICATION_URL}
    restart: unless-stopped
volumes:
  prometheus-data:
  grafana-data:
